### ISSUE TITLE
Shivam Patel

### ISSUE THREAD

**Issue by FlippyShivam** [VIP-SMUR/24Fa-EnergyInBuildings-Res#4]
Weekly Notebook Entry — Week [Number]
Quick Overview
List your top 3 tasks or objectives for this week:

Task 1:
Task 2:
Task 3:
Weekly Accomplishments
What tasks did you complete this week? (Include links)
Tasks are still ongoing? Current status?
Challenges and Learning
What was the biggest challenge you faced this week? How did you address it?
What's one new thing you learned or skill you improved?
Did you attend any team meetings? Key takeaways?
Reflection and Planning
Your progress this week?
Main focus for next week?
Any resources you're looking for?

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [Number]

### Overview
- **Week Span:** `[Start Date]` to `[End Date]`

### Tasks for This Week
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.


### Tasks

##### Task: [Task Name] -  _(completed)_
- **Description:** 
- **Link to Work:** [Link](#)
- **Outcome & Reflection:** 

##### Task: [Task Name] - _(ongoing)_
- **Current Status:** 
- **Expected Completion:** 

### Challenges & Solutions
- 

### General Takeaway, Skills & Knowledge Acquired
- 

### Team Meetings
- **Meeting Highlights:** 
- **Peer Feedback:** 

### Personal Reflection
- 

### Visual Documentation (optional)


### Additional Notes & Resources (optional)

- [Resource Name](URL) - Brief description.

---

### Plans for Next Week
- [ ] Next Week's Task 1: Description and strategy.

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [2]

### Quick Overview
     This week we all got our assigned teams, and started the onboarding process on what we all did last semester (Spring 24).
### Top tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Have a call with new team members to onboard them and explain what the team and project goals are, and rundown on what was accomplished.

### Weekly Accomplishments
 Held multiple meetings to discuss updates on what research everyone has done. Last team was all CS, and now we have more diversity with architecture students and CS students. 
###Tasks completed
Held meetings, and created respective team group chats for people to get to know each other and communicate goals. 
### Tasks ongoing
Teach how computational modeling works, and overview on what we looked for. 
### Challenges & Learning
Most people do not come from a CS background, so it was important to teach them how this modeling project whilst also taking inputs to better understand architectural play as I do not have much experience in that. 
### Biggest Challenge
Onboarding and playing catch up

### Takeaway, Learning
-  We may have to spend 1-2 weeks to go over what we did last year and explain core modeling concepts. 


### Main Focus next week
Possibly have a workshop to discuss how the Multivariate model was synthesized. 

### Resources
https://github.com/VIP-SMUR/24Sp-EnergyInBuildings

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [3]

### Quick Overview
We continued research on modeling and explaining it more in-depth
### Top tasks

- [ ] Task 1: Reviewed papers so I can catch up on the reading, and also looked into PACE again (need access to rerun)
- [ ] Task 2:  Have in depth meeting for model explanation.

### Weekly Accomplishments
-Read through some papers, and also held meetings to catch up on what exactly residential may look for over commercial. 
-Held long meeting to explain further detail how Machine learning works. 
### Tasks completed
Read resources and held meeting
### Tasks ongoing
Onboarding, and attempting to still run ASHRAE
### Challenges & Learning
ASHRAE is still taking a while, may have to communicate with Dr.Kastner how it may be a lost cause because it takes a long time anyway. 
### Biggest Challenge
-  Now with the split of the team, finding out what specific task we should attack. While it is understood we will now look into heating/cooling outputs at a residential level, understanding the specifics of how we will reach is still undecided. 

### Takeaway, Learning
-In-Depth Model Meeting (09/12): reviewed models more in depth, understood that the ASHRAE model is most likely too involved for this project

-Meeting w/ Prof. Kastner (09/13): Start looking into a creating a grasshopper script to create a synthetic dataset to train the model.

### Reflection & Planning
Everyone gained a better understanding of project.
### Progress
-One final push on ASHRAE, if not the focus on models we have now, like Multivariate. 

### Main Focus next week
Now build an understanding on how we will tackle residential heating/cooling outputs. 

### Resources
none

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [4]

### Quick Overview
Attempt to create synthetic data, with some created via parametric grasshopper script or via https://www.mockaroo.com/
### Top tasks

- [ ] Task 1: Gave final run on ASHRAE, then decided its bets to move forward with Multivariate. Attempting to run it and get an understanding on how it works. 

### Weekly Accomplishments
I am confused on why we use synthetic data, when we want to train model with real data. 
### Tasks completed
Built understanding on synthetic data

### Biggest Challenge
- I'm not to sure on what we are trying to do or where we want to head now. 

### Takeaway, Learning
- Talked with Hang and Dr. Kastner. Built understanding that synthetic data would be good to create the pipeline for the project and then we can worry about collecting more robust data. 

### Reflection & Planning
- Group Meeting (09/17): Have a better understanding of what we need to do as a group, look into Honeybee tutorials
- Meeting w/ Prof. Kastner (09/20): Look at example parametric script from Prof. Kastner, look into ResStock

### Progress
- We may look into creating parametric data, so waiting on data validation to then see where to go further. 

### Main Focus next week

Collect data then run a base model to see what we can get from Multivariate

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [5]

### Quick Overview
Look into ResStock Data, and then understand which variable may be useful. (There are many inputs and outputs). 

### Top tasks

- [ ] Task 1: Grab potential data, and choose which ones we may want
- [ ] Task 2: Run data analysis on those columns, then see if I can run Multivariate on it. 

### Weekly Accomplishments
 Ended up running Multivariate Model on 7 variables:


### Tasks completed
Did analysis on 

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [6]

### Quick Overview
Met team to discuss how to create a better dataset out of ResStock, understand what some variables could mean, and which inputs to run in Multivariate. 
### Top 3 tasks

- [ ] Task 1: Get another list of better columns to test for Multivariate, and then also see what columns we can manipulate and create (like getting IDF and dimensions) to then see what impact it has. 

### Weekly Accomplishments
Getting further in parametric in grasshopper, so hopefully we can run them and see if we get better results for outputs.

### Tasks completed
Got a little busy with midterms, hopefully will try to do weekend.

### Challenges & Learning
Now we must focus on the math and analysis of the data. ResStock does not give full dimensions, so we must combine our information and see of we can create simulated data and see if it has better correlation. (Big one is orientation). 
### Biggest Challenge
- Fixing orientational effects on energy output. 

### Takeaway, Learning
- We want more emphasis on heating and cooling over other outputs. 

### Reflection & Planning


### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [7]

### Quick Overview

### Top 3 tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
- [ ] Task 2: 
- [ ] Task 3:

### Weekly Accomplishments

### Tasks completed

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [8]

### Quick Overview

### Top 3 tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
- [ ] Task 2: 
- [ ] Task 3:

### Weekly Accomplishments

### Tasks completed

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [9]

### Quick Overview

### Top 3 tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
- [ ] Task 2: 
- [ ] Task 3:

### Weekly Accomplishments

### Tasks completed

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [10]

### Quick Overview

### Top 3 tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
- [ ] Task 2: 
- [ ] Task 3:

### Weekly Accomplishments

### Tasks completed

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [11]

### Quick Overview

### Top 3 tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
- [ ] Task 2: 
- [ ] Task 3:

### Weekly Accomplishments

### Tasks completed

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources

**Comment by FlippyShivam** [comment]
## Weekly Notebook Entry — Week [12]

### Quick Overview

### Top 3 tasks
List your specific objectives for this week, including learning targets and project milestones.
- [ ] Task 1: Detailed description and expected outcome.
- [ ] Task 2: 
- [ ] Task 3:

### Weekly Accomplishments

### Tasks completed

### Tasks ongoing

### Challenges & Learning

### Biggest Challenge
- 

### Takeaway, Learning
- 

### Reflection & Planning

### Progress
- 

### Main Focus next week


### Resources
